## Preprocessing

In [31]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [32]:
# Get the column names as a list
column_names = list(application_df.columns)

# Print the column names
print("Column names:", column_names)

Column names: ['EIN', 'NAME', 'APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION', 'USE_CASE', 'ORGANIZATION', 'STATUS', 'INCOME_AMT', 'SPECIAL_CONSIDERATIONS', 'ASK_AMT', 'IS_SUCCESSFUL']

In [33]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(columns=['EIN', 'NAME'], inplace=True, axis=1)
#note axis means horizonal vs vertical, 0 is horizontal,
#note inplace true means overwrite the original DataFrame, if you dont wanna do this make a copy

In [34]:
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [35]:
# Calculate the number of unique values in each column
unique_values_per_column = application_df.nunique()

# Print the number of unique values for each column
print("Number of unique values in each column:")
print(unique_values_per_column)

Number of unique values in each column:
APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [36]:
# Look at APPLICATION_TYPE value counts for binning
binned_application_types = application_df['APPLICATION_TYPE'].value_counts()
binned_application_types

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [37]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
cutoff_value = 500
application_types_to_replace = binned_application_types[binned_application_types< cutoff_value].index


# Replace in dataframe
for app in application_types_to_replace:

 application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [38]:
# Look at CLASSIFICATION value counts for binning
binned_classification = application_df['CLASSIFICATION'].value_counts()

In [39]:
# You may find it helpful to look at CLASSIFICATION value counts >1
cutoff_value = 51
classification_greater_one = binned_classification[binned_classification> cutoff_value]
classification_greater_one
print(classification_greater_one)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
Name: CLASSIFICATION, dtype: int64

In [40]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
cutoff_value = 58
classifications_to_replace = binned_classification[binned_classification< cutoff_value].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      441
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
Name: CLASSIFICATION, dtype: int64

In [44]:
# Convert categorical data to numeric with `pd.get_dummies`
application_df = pd.get_dummies(application_df)
application_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [45]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
X = application_df.copy()
X.drop("IS_SUCCESSFUL", axis=1, inplace=True)

y = application_df["IS_SUCCESSFUL"].values.reshape(-1, 1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

X.head()

,STATUS,ASK_AMT,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,0,0,0,1,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,0,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,0,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [46]:
y[:5]

array([[1],
       [1],
       [0],
       [1],
       [1]])

In [50]:
X.shape

(34299, 52)

In [47]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [51]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()

nn.add(tf.keras.layers.Dense(units=80, activation="relu", input_dim=52))
# First hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 80)                4240

 dense_5 (Dense)             (None, 30)                2430

 dense_6 (Dense)             (None, 30)                930

 dense_7 (Dense)             (None, 1)                 31

=================================================================
Total params: 7631 (29.81 KB)
Trainable params: 7631 (29.81 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [52]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [53]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 1ms/step - loss: 0.5715 - accuracy: 0.7202
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5527 - accuracy: 0.7311
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5498 - accuracy: 0.7329
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5474 - accuracy: 0.7335
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5463 - accuracy: 0.7343
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5454 - accuracy: 0.7362
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5440 - accuracy: 0.7352
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5435 - accuracy: 0.7369
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7357
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5419 - accuracy: 0.7371
Epoch 11/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5415 - accuracy: 0.7370
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5418 - accuracy: 0.7379
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5410 - accuracy: 0.7374
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5404 - accuracy: 0.7382
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5396 - accuracy: 0.7390
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5393 - accuracy: 0.7379
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5394 - accuracy: 0.7389
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5391 - accuracy: 0.7390
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5385 - accuracy: 0.7391
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5386 - accuracy: 0.7397
Epoch 21/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5384 - accuracy: 0.7384
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7384
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7393
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5374 - accuracy: 0.7399
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5368 - accuracy: 0.7403
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5370 - accuracy: 0.7405
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5367 - accuracy: 0.7399
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7404
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5358 - accuracy: 0.7406
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5359 - accuracy: 0.7402
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5360 - accuracy: 0.7403
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7402
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5356 - accuracy: 0.7416
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5354 - accuracy: 0.7401
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5355 - accuracy: 0.7411
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5350 - accuracy: 0.7411
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5349 - accuracy: 0.7413
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5346 - accuracy: 0.7407
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5343 - accuracy: 0.7418
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5345 - accuracy: 0.7411
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5340 - accuracy: 0.7414
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5339 - accuracy: 0.7409
Epoch 43/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5342 - accuracy: 0.7409
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7419
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7412
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5335 - accuracy: 0.7412
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5338 - accuracy: 0.7415
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5334 - accuracy: 0.7422
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5330 - accuracy: 0.7422
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5331 - accuracy: 0.7410
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7416
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5329 - accuracy: 0.7420
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5328 - accuracy: 0.7419
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5332 - accuracy: 0.7419
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5328 - accuracy: 0.7421
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5326 - accuracy: 0.7424
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7423
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5323 - accuracy: 0.7426
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7424
Epoch 60/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5319 - accuracy: 0.7421
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5320 - accuracy: 0.7426
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5323 - accuracy: 0.7418
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5321 - accuracy: 0.7414
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5319 - accuracy: 0.7414
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5316 - accuracy: 0.7421
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5318 - accuracy: 0.7424
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7428
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5315 - accuracy: 0.7432
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5313 - accuracy: 0.7428
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5313 - accuracy: 0.7430
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5317 - accuracy: 0.7427
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5312 - accuracy: 0.7428
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7421
Epoch 74/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5312 - accuracy: 0.7432
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7427
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7421
Epoch 77/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5317 - accuracy: 0.7434
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7423
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5307 - accuracy: 0.7430
Epoch 80/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5320 - accuracy: 0.7425
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5307 - accuracy: 0.7422
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7439
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5305 - accuracy: 0.7431
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5308 - accuracy: 0.7426
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5304 - accuracy: 0.7423
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7433
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7422
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5305 - accuracy: 0.7433
Epoch 89/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7428
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5301 - accuracy: 0.7432
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5304 - accuracy: 0.7430
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5303 - accuracy: 0.7428
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5296 - accuracy: 0.7427
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5302 - accuracy: 0.7436
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5302 - accuracy: 0.7428
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7428
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5301 - accuracy: 0.7428
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5302 - accuracy: 0.7426
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7431
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5296 - accuracy: 0.7439

In [54]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5557 - accuracy: 0.7279 - 566ms/epoch - 2ms/step
Loss: 0.5556613206863403, Accuracy: 0.7279300093650818

In [55]:
# Export our model to HDF5 file
nn.save("Deep_learning_challenge_completed.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(